#!/usr/bin/python
# -*- coding: utf-8 -*-

########################################################################
#                                                                      #
# PyDict - a python client for Dict.CN                                 #
#                                                                      #
# Copyright (C)2008-2008 Dongsheng Cai                                 #
#                                                                      #
########################################################################
#                                                                      #
# This program is free software; you can redistribute it and/or modify #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation; either version 2 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# This program is distributed in the hope that it will be useful,      #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #
# GNU General Public License for more details.                         #
#                                                                      #
########################################################################

import sys
import ConfigParser

app_name     = 'PyDict';
version      = '0.2';
author       = 'Dongsheng Cai';
author_email = 'me@dongsheng.org';

# ANSI sequences for colours
CLR_SEQ = {
    'white'       : "\033[1;37m",
    'yellow'      : "\033[1;33m",
    'green'       : "\033[1;32m",
    'blue'        : "\033[1;34m",
    'cyan'        : "\033[1;36m",
    'red'         : "\033[1;31m",
    'magenta'     : "\033[1;35m",
    'black'       : "\033[1;30m",
    'darkwhite'   : "\033[0;37m",
    'darkyellow'  : "\033[0;33m",
    'darkgreen'   : "\033[0;32m",
    'darkblue'    : "\033[0;34m",
    'darkcyan'    : "\033[0;36m",
    'darkred'     : "\033[0;31m",
    'darkmagenta' : "\033[0;35m",
    'darkblack'   : "\033[0;30m",
    'off'         : "\033[0;0m"
}

def format(cell):
    cell['word'] = color(cell['word'], 'red')
    print cell['word']
    if cell.has_key('pron'):
        cell['pron'] = color(cell['pron'], 'blue')
        print '[' + cell['pron'] + ']'
    for i in cell['def']:
        i = color(i.lower(), 'darkyellow');
        print i
    print '============'

    if cell.has_key('sentences'):
        for i in cell['sentences']:
            print 'O: ' + color(i['o'], 'darkcyan')
            print 'T: ' + color(i['t'], 'darkmagenta')
            print '======'

    return cell

def color(str, clr):
    if not clr:
        return str;
    else:
        return CLR_SEQ[clr] + str + CLR_SEQ['off']

def pydict(dict_type, options):
    exec "from type_" + dict_type + " import dict"
    dict_engine = dict(options)
    result = dict_engine.get_result(options['word'])
    format(result)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print u'PyDict: No arguments entered.'
        sys.exit(0)
    else:
        searchword = sys.argv[1]
	
	config = ConfigParser.RawConfigParser()
	config.read(sys.path[0] + '/dict.ini')
	dict_type = config.get('pydict', 'type')
	dict_data = config.get('pydict', 'dict')
    options = {}
    options['word'] = searchword
    options['dict_data'] = dict_data
    if not dict_type:
        dict_type = 'dictcn'
    pydict(dict_type, options);

